name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test
    - name: Run Linter
      run: cargo clippy
    - name: Check format
      run: cargo fmt --check
    - name: Build in release mode
      run: cargo build --release
    - uses: actions/upload-artifact@v3
      with:
        name: dotfile
        path: target/x86_64-unknown-linux-musl/release/dotfile
