name: Check

on:
  push:
    branches: [ "master" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test
    - name: Run Linter
      run: cargo clippy
    - name: Check format
      run: cargo fmt --check
  release:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install musl-tools
        run: sudo apt-get update && sudo apt-get -y install musl-tools
      - name: Add the musl target build pipeline
        run: rustup target add x86_64-unknown-linux-musl
      - name: Build in release mode
        run: cargo build --release --target x86_64-unknown-linux-musl
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "target/x86_64-unknown-linux-musl/release/dotfile"
          bodyFile: "body.md"