name: Check

on:
  push:
    branches: [ "master" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: cargo test
    - name: Run Linter
      run: cargo clippy
    - name: Check format
      run: cargo fmt --check
  release:
    needs: check
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Install musl-tools and UPX
        run: sudo apt-get update && sudo apt-get -y install upx podman
      - name: Install the cross compiler for rust
        run: cargo install cross --git https://github.com/cross-rs/cross
      - name: Cross build aarch64
        run: cross build --target aarch64-unknown-linux-musl --release
      - name: Cross build x86_64
        run: cross build --target x86_64-unknown-linux-musl --release
      - name: Pack the files
        run: upx target/x86_64-unknown-linux-musl/release/dotfile && upx target/aarch64-unknown-linux-musl/release/dotfile -o target/aarch64-unknown-linux-musl/release/dotfile.aarch64
      - name: Generate the help file and check the packed binary
        run: echo '```' > help.md && target/x86_64-unknown-linux-musl/release/dotfile --help >> help.md && echo '```' >> help.md
      - uses: ncipollo/release-action@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          artifacts: "target/x86_64-unknown-linux-musl/release/dotfile,target/aarch64-unknown-linux-musl/release/dotfile.aarch64"
          bodyFile: "help.md"