name: Check

on:
  push:
    branches: [ "master" ]
    tags: [ '*' ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install docker
      run: sudo apt-get update && sudo apt-get -y install podman
    - name: Install cross compiler for rust
      run: cargo install cross --git https://github.com/cross-rs/cross
    - name: Cross build
      run: cross build --target aarch64-unknown-linux-musl
    - name: What has been built
      run:  ls -R target/